FROM python:3.10-slim

WORKDIR /app

COPY frontend/requirements_fe.txt .
RUN pip install --default-timeout=1000 --no-cache-dir -r requirements_fe.txt


COPY frontend/ ./frontend/

EXPOSE 8501

# Put the entire CMD array on exactly one line
CMD ["streamlit", "run", "frontend/app_ui.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]