FROM python:3.10-slim

WORKDIR /app

COPY frontend/requirements_fe.txt .
RUN pip install --no-cache-dir -r requirements_fe.txt

COPY frontend/ ./frontend/

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app_ui.py",
"--server.port=8501", "--server.address=0.0.0.0",
"--server.headless=true"]